#!/bin/bash
[ -z $TFTP_PATH ] && TFTP_PATH=/data/

chmod o+rwx $TFTP_PATH

/usr/sbin/atftpd --daemon --no-fork --tftpd-timeout 300 --retry-timeout 5 --mcast-port 1758 --mcast-addr 239.239.239.0-255 --mcast-ttl 1 --maxthread 100 --verbose=5 $TFTP_PATH


